---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aluno-api
  namespace: aluno-api
  labels:
    app: aluno-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aluno-api
  template:
    metadata:
      labels:
        app: aluno-api
    spec:
      containers:
        - name: aluno-api
          image: brunodsfreitas/aluno-project-api:v0.1.1
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: aluno-api-service
spec:
  selector:
    app: aluno-api
  ports:
  - protocol: TCP
    port: 3000
  type: LoadBalancer