---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aluno-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/brunodsfreitas/aluno-project.git
    targetRevision: master
    path: env/dev/aluno-api
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true