name: CD - Deploy to EKS Cluster

on:
  workflow_run:
    workflows: ["CI - Build Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials and tools for EKS
        uses: aws/eks-anywhere-setup@v1
        with:
          eks-version: "1.29"  # Versão do Kubernetes do cluster EKS
          eks-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Chave de acesso da AWS
          eks-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Chave secreta da AWS
          eks-region: "us-east-2"  # Região da AWS onde o cluster EKS está localizado

      - name: Deploy to EKS
        run:
          kubectl apply -f env/dev/aluno-api/deployment.yaml --force
