name: CI - Build Docker Image

on:
    push:
      branches:
        - master

env: 
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

#    - name: Build Docker image
#      run: docker build -t brunodsfreitas/aluno-project-api:dev -f api.dockerfile .

    - name: Docker Login
      run: 
        echo "DOCKER_USERNAME secret value= ${{secrets.DOCKER_USERNAME}} "
        echo ${{ secrets.DOCKER_USERNAME }} | sed 's/./& /g'

#        ./ci-login.sh
        
#    - name: Push Docker image
#      run: docker push brunodsfreitas/aluno-project-api:dev